### ISSUE TITLE
How to run the Developer Tools?

### ISSUE THREAD

**Issue by Kornelis** [Microsoft/windows-admin-center-sdk#26]
Hi,

first of all, I'm pretty new to Angular and Typescript so my question might be a bit noob-ish...

I just cloned the sdk repo and tried to build the Developer Tools which told me to not Build the Sample but create a new Extension using the CLI and "reference?" example source.

So I just created a new Extension using the CLI and tried to Sideload it into Admin Center which then showed the string "Congratulations, you have now created a new Windows Admin Center extension!". So basicly I was able to sideload a new Extension.

Then I removed the "src" Folder of my created Extension and copied the "src" Folder from the Developer Tools over to my Extension. After fixing an Issue in the alert-bar-example Component the build was successfull. When starting the Server with "Gulp serve" everyhing seemed to work fine, but when trying to sideload the modified Extension I doesn't even show up as sideloaded extension. There is not even an error Message in the Output.

So what do I have to do to get the Dev Tools working from wihin Admin Center?

A more step by step guide of "how to run the Dev Tools" would be nice instead of linking to the Documentation of how to create an empty extension.

Thanks and kind regards

**Comment by mattatmsft** [comment]
Hi Kornelis - 

The Dev Tools repo is mostly left up for a reference, rather than a download and run.  Basically we want it to be a easy way to copy and paste some of the controls into your own extensions.  If you want to see it running, we have an extension published to the Extension Feed.  Check out this article: https://docs.microsoft.com/en-us/windows-server/manage/windows-admin-center/configure/using-extensions

When you get to the Available Extensions, just look for "Windows Admin Center Developer Tools (Preview)", select, and then install.
