### ISSUE TITLE
WAC should has ability to instruct powershell to connect client via port 80 

### ISSUE THREAD

**Issue by tlsalex** [microsoft/windows-admin-center-sdk#55]
Hello, what I understand is windows admin center using PowerShelI to connect to targets ,that is manage target via Powershell , However,in my case, the default port 5985 is block by security software on my windows 10 client. But winrm can listen on 5985 and 80 at the same time, by enable EnableCompatibilityHttpListener ,than poewershell can reach remote target with 80 , but in WAC there is no way to instruct powershell to use another port ,only the default behavior.WAC should make an improvement on this matter.

-- This is the second time for this question , I hope someone can give me some tips

**Comment by mattatmsft** [comment]
Hi - your understanding is correct, but at this point in time, Windows Admin Center does not support anything but the default ports for WinRM, and even then it's just 5985.  This is built into the platform at initialization time.  I agree that it would be an incredibly awesome feature to be able to specify custom WinRM ports, this would be incredibly useful!  

We take new features from our feedback site found on [our feedback site here](http://aka.ms/wacfeedback).  For platform level requests and suggestions (which this is), please use this site.  In fact, this type of request [is already covered here]( https://windowsserver.uservoice.com/forums/295071-management-tools/suggestions/33981802--configuration-winrm-connect-using-non-default), Please vote on this one so that we can get it into our backlog.

This repo is just code examples for the SDK, showing how to build extensions.
